# Tugas Praktikum

- Lakukan klasifikasi pada data MNIST dengan menggunakan model ANN
- Anda diperbolehkan melakukan eksplorasi terhadap,
  - Metode pra pengolahan
  - Pemilihan fitur
  - Arsitektur ANN
  - Fungsi Aktiviasi
- ANN diimplementasikan dengan menggunakan tensorflow.
- DIKERJAKAN SECARA BERKELOMPOK
- JELASKAN HASIL YANG ANDA DAPATKAN,
  - AKURASI
  - CONFUSION MATRIX
  - KONFIGURASI MODEL --> MULAI DARI PRA PENGOLAHAN SAMPAI ARSITEKTUR ANN

### Langkah 1 - Import Library

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

### Langkah 2 - Pra-pengolahan data MNIST

In [2]:
# Pra-pengolahan data
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data() # load data MNIST dan split data

# ubah bentuk fitur menjadi vektor dan dinormalisasi
x_train = x_train.reshape(-1, 784).astype("float32") / 255.0
x_test = x_test.reshape(-1, 784).astype("float32") / 255.0

### Langkkah 3 - Buat Arsitektur ANN

In [3]:
# Arsitektur ANN
# Terdiri dari 3 lapisan Dense dengan funsi aktivasi ReLU
ann = keras.Sequential(
    [
        layers.Dense(256, activation="relu"),
        layers.Dense(128, activation="relu"),
        layers.Dense(10),
    ]
)


### Langkah 4 - Buat Fugsi Aktivasi

In [4]:
# Fungsi aktivasi
ann.compile(
    optimizer=keras.optimizers.Adam(0.001),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
)

### Langkah 5 - Latih Model ANN dan Lakukan Evaluasi Model

In [5]:
# Pelatihan model
# Model dilatih menggunakan data latih dengan batch size 32 dan epoch sebanyak 5 kali.
ann.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)

# Evaluasi model
# Model dievaluasi menggunakan data uji dan menghitung akurasi.
test_loss, test_acc = ann.evaluate(x_test, y_test, verbose=2)
print("Test accuracy:", test_acc)

Epoch 1/5
1875/1875 - 6s - loss: 0.2094 - accuracy: 0.9366 - 6s/epoch - 3ms/step
Epoch 2/5
1875/1875 - 5s - loss: 0.0864 - accuracy: 0.9731 - 5s/epoch - 3ms/step
Epoch 3/5
1875/1875 - 5s - loss: 0.0586 - accuracy: 0.9814 - 5s/epoch - 3ms/step
Epoch 4/5
1875/1875 - 5s - loss: 0.0436 - accuracy: 0.9857 - 5s/epoch - 3ms/step
Epoch 5/5
1875/1875 - 5s - loss: 0.0344 - accuracy: 0.9887 - 5s/epoch - 3ms/step
313/313 - 1s - loss: 0.0784 - accuracy: 0.9779 - 725ms/epoch - 2ms/step
Test accuracy: 0.9779000282287598


### Langkah 6 - Tampilkan Confusion Matrix

In [6]:
# Confusion matrix
# Confusion matrix dihitung menggunakan data uji dan prediksi model.
y_pred = ann.predict(x_test)
confusion_matrix = tf.math.confusion_matrix(y_test, tf.argmax(y_pred, axis=1))
print("Confusion matrix:\n", confusion_matrix)

313/313 [==============================] - 1s 2ms/step
Confusion matrix:
 tf.Tensor(
[[ 973    0    1    0    1    0    2    1    2    0]
 [   0 1124    3    0    0    1    2    0    5    0]
 [   5    0 1002    2    1    0    1    8   12    1]
 [   2    0    0  993    0    2    0    5    5    3]
 [   1    1    3    0  952    0    6    2    1   16]
 [   4    0    0   10    1  866    2    2    5    2]
 [  10    3    0    0    3    7  926    3    6    0]
 [   1    3    7    1    1    0    0 1006    5    4]
 [   4    1    3    6    1    4    0    4  950    1]
 [   4    2    0    0    4    2    0    5    5  987]], shape=(10, 10), dtype=int32)
